// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz1Z0qgERar5Tl0V1Q9Me9yyuoKeytnSc',
    appId: '1:35223905945:web:6b4cd3be1e3dfc10073a08',
    messagingSenderId: '35223905945',
    projectId: 'biometric-app-bc897',
    authDomain: 'biometric-app-bc897.firebaseapp.com',
    storageBucket: 'biometric-app-bc897.firebasestorage.app',
    measurementId: 'G-LNKRBM70NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDywdX-r6oaMXSyJZXQgHF4GfV8vncrbo0',
    appId: '1:35223905945:android:3976242c3fc33389073a08',
    messagingSenderId: '35223905945',
    projectId: 'biometric-app-bc897',
    storageBucket: 'biometric-app-bc897.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8qSaTL77Ql7Cm2FzeZCFLD8k-WhaAJOk',
    appId: '1:35223905945:ios:7ad6dbd5b558dc17073a08',
    messagingSenderId: '35223905945',
    projectId: 'biometric-app-bc897',
    storageBucket: 'biometric-app-bc897.firebasestorage.app',
    iosBundleId: 'com.example.biometric-app',
  );
}
