name: biometric_app
description: A Biometric Dashboard
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  app_ui:
    path: ../app_ui
  bloc: ^9.0.0
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_crashlytics: ^5.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.2.0
  go_router: ^16.2.2
  intl: ^0.20.2
  loader_overlay: ^5.0.0
  logger: ^2.6.1
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^31.2.3


dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/gifs/
    - config/development.json
    - config/staging.json
    - config/production.json
    - assets/data/biometrics_90d.json
    - assets/data/journals.json
